spring.application.name=gh-51463-reproducer
spring.threads.virtual.enabled=true
spring.main.keep-alive=true
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
server.shutdown=immediate
